# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherIf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('numb', models.CharField(max_length=20, verbose_name='工号')),
                ('service', models.CharField(max_length=200, verbose_name='负责业务')),
            ],
        ),
    ]
