# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170320_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='active',
        ),
        migrations.AddField(
            model_name='ad',
            name='active',
            field=models.BooleanField(default=True, verbose_name='是否发表'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
    ]
