# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170320_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='ImageField',
            new_name='picurl',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='url',
        ),
        migrations.AddField(
            model_name='comment',
            name='jobnum',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='工号'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
    ]
