# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170321_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['id'], 'verbose_name': '业务担当', 'verbose_name_plural': '业务担当'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
    ]
