# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170321_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={},
        ),
        migrations.AddField(
            model_name='master',
            name='where',
            field=models.CharField(blank=True, choices=[('休息', '休息'), ('上班', '上班')], max_length=4, null=True, verbose_name='是否上班'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
    ]
