# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20170321_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.CharField(choices=[('计算机相关问题', '计算机相关问题'), ('会议相关问题', '会议相关问题'), ('电话相关问题', '电话相关问题'), ('视频监控相关问题', '视频监控相关问题'), ('餐卡相关问题', '餐卡相关问题')], default='计算机相关问题', max_length=20, verbose_name='故障')),
                ('eventdetail', models.TextField(blank=True, verbose_name='故障描述')),
                ('jindu', models.CharField(choices=[('创建', '创建'), ('等待处理', '等待处理'), ('已受理', '已受理'), ('结束', '结束')], default='创建', max_length=20, verbose_name='进度')),
                ('username', models.CharField(max_length=30, verbose_name='你的名字')),
                ('worker', models.CharField(default='IT', max_length=30, verbose_name='IT受理人')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新')),
                ('grade', models.CharField(choices=[('菜鸟', '菜鸟'), ('高手', '高手'), ('大师', '大师'), ('宗师', '宗师'), ('神', '神')], default='宗师', max_length=20, verbose_name='评价')),
                ('gradetext', models.TextField(blank=True, verbose_name='建议')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
    ]
