# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20170322_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-created',), 'verbose_name': '故障', 'verbose_name_plural': '故障'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='event',
            name='jindu',
            field=models.CharField(choices=[('创建', '创建'), ('已受理', '已受理'), ('结束', '结束')], default='创建', max_length=20, verbose_name='进度'),
        ),
        migrations.AlterField(
            model_name='event',
            name='username',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
    ]
