# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20170322_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='位置'),
        ),
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(max_length=30, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='event',
            name='jobnum',
            field=models.CharField(max_length=10, null=True, verbose_name='工号'),
        ),
        migrations.AddField(
            model_name='event',
            name='mobile',
            field=models.CharField(max_length=11, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='event',
            name='username',
            field=models.CharField(max_length=30, null=True, verbose_name='姓名'),
        ),
    ]
