# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20170322_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='event',
            name='grade',
            field=models.CharField(choices=[('菜鸟', '菜鸟'), ('高手', '高手'), ('大师', '大师'), ('宗师', '宗师'), ('神', '神')], default=None, max_length=20, verbose_name='评价'),
        ),
        migrations.AlterField(
            model_name='event',
            name='jindu',
            field=models.BooleanField(default=False, verbose_name='收否结束'),
        ),
    ]
