# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20170323_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='event',
            name='grade',
            field=models.CharField(blank=True, choices=[('菜鸟', '菜鸟'), ('高手', '高手'), ('大师', '大师'), ('宗师', '宗师'), ('神', '神')], max_length=20, null=True, verbose_name='评价'),
        ),
    ]
